[package]
name = "feat"
version = "0.1.0"
description = "local-first cli task tracking"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
error-report = "0.0.1"
rusqlite = "0.31.0"
rusqlite_migration = { version = "1.2.0", features = ["from-directory"] }
